name: Docker Image CI

# Build all branches and PRs
# Push only in main (:latest) and tags (:vX.Y.Z)

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - github.event.repository.default_branch

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/gameslist
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./
          push: ${{ github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
